/*
 * launcherDialog.java
 *
 * Created on 30.11.2010, 7:33:05
 */

package gen_seq;

import gen_seq.generator.*;
import java.util.logging.*;
import java.util.zip.*;
import javax.swing.*;

/**
 *
 * @author akademi4eg
 */
public class launcherDialog extends JDialog {

    /** Creates new form launcherDialog */
    public launcherDialog(GenFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(btnLaunch);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPopLen = new javax.swing.JFormattedTextField();
        txtChrLen = new javax.swing.JFormattedTextField();
        btnCancel = new javax.swing.JButton();
        btnLaunch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCorr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generation parameters");
        setModal(true);
        setName("launcherDg"); // NOI18N
        setResizable(false);

        jLabel1.setText("Population size");
        jLabel1.setToolTipText("Number of elements in population.");

        jLabel2.setText("Chromosome length");

        txtPopLen.setColumns(3);
        txtPopLen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtPopLen.setText("5");
        txtPopLen.setToolTipText("Number of elements in population.");

        txtChrLen.setColumns(8);
        txtChrLen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtChrLen.setText("1000");
        txtChrLen.setToolTipText("Number og genes in chromosome");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnLaunch.setText("Launch");
        btnLaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaunchActionPerformed(evt);
            }
        });

        jLabel3.setText("Correlator C(r)=");

        txtCorr.setText("0.25*exp(-r)");
        txtCorr.setToolTipText("Enter correlator here.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(63, Short.MAX_VALUE)
                        .addComponent(btnLaunch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPopLen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChrLen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(txtPopLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtChrLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaunch)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaunchActionPerformed
        if (Integer.parseInt(txtPopLen.getText()) <= 0)
        {
            JOptionPane.showMessageDialog(this, "Population size must be positive!", "Validation error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Integer.parseInt(txtChrLen.getText()) <= 0)
        {
            JOptionPane.showMessageDialog(this, "Chromosome length must be positive!", "Validation error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        EtalonCorrelator.getParser().addVariable("r", 1);
        EtalonCorrelator.getParser().parseExpression(txtCorr.getText());// Parse the expression
        if (EtalonCorrelator.getParser().hasError()) {
            JOptionPane.showMessageDialog(this, "Error while parsing expression for correlator. "+EtalonCorrelator.getParser().getErrorInfo(), "Validation error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        EtalonCorrelator.expression = txtCorr.getText();
        
        ((GenFrame)getParent()).lockElementsDueToLaunch();
        // starting population
        new Thread(new Runnable() {
            public void run() {
                try {
                    Population.getInstance().setLength(Integer.parseInt(txtPopLen.getText()));
                    Population.getInstance().setChromosomeLength(Integer.parseInt(txtChrLen.getText()));
                    Population.getInstance().init();

                    ((GenFrame) getParent()).updateStats(StatsCollector.POPULATION_LENGTH, Integer.toString(Population.getInstance().getLength()));
                    ((GenFrame) getParent()).updateStats(StatsCollector.CHROMOSOME_LENGTH, Integer.toString(Population.getInstance().getChromosomeLength()));
                    ((GenFrame) getParent()).initStatsTable(Population.getInstance().getLength());
                    
                    Population.getInstance().setActive(true);
                    Population.getInstance().setRunning(true);

                    Chromosome filler;
                    while (Population.getInstance().isRunning())
                    {
                        if (!Population.getInstance().isActive()) continue;
                        Population.getInstance().evolve();
                        filler = Population.getInstance().getBest();
                        if (Population.getInstance().getBestAchievement().getFitness() < filler.getFitness())
                            filler = Population.getInstance().getBestAchievement();
                        Population.getInstance().fill(filler);
                    }

                    ((GenFrame)getParent()).unlockElementsDueToLaunch();
                } catch (DataFormatException ex) {
                    Logger.getLogger(launcherDialog.class.getName()).log(Level.SEVERE, null, ex);
                    ((GenFrame)getParent()).unlockElementsDueToLaunch();
                }
            }
        }).start();

        // starting stats collector
        new java.util.Timer().schedule(new StatsCollector((GenFrame) getParent()), StatsCollector.DELAY, StatsCollector.DELAY);
                    
        dispose();
    }//GEN-LAST:event_btnLaunchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLaunch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtChrLen;
    private javax.swing.JTextField txtCorr;
    private javax.swing.JFormattedTextField txtPopLen;
    // End of variables declaration//GEN-END:variables

}
